config/routes.rb
Rails.application.routes.draw do
  get "signin" => "sessions#new"
  resource :session
  get 'signup' => 'users#new'
  resources :users

  root "open_mats#index"
  resources :open_mats do 
    resources :registrations
  end
end

app/models/open_mat.rb
class OpenMat < ActiveRecord::Base

  validates :location, :host, :starts_at, presence: true

  validates :number_people_attending, numericality: { greater_than_or_equal_to: 0 }

  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  has_many :registrations, dependent: :destroy

  def expired?
    starts_at < Time.now
  end

  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")
  end
end

app/models/registration.rb
class Registration < ActiveRecord::Base

  validates :name, :affiliation, presence: true

  validates :email, format: { with: /(\S+)@(\S+)/ }

  BELT_LEVEL_OPTIONS = [
    'White',
    'Blue',
    'Purple',
    'Brown',
    'Black'
  ]

  validates :belt_level,
            inclusion: { in:  BELT_LEVEL_OPTIONS }

  GENDER_OPTIONS = [
    'M',
    'F',
    'Other'
  ]

  validates :gender,
            inclusion: { in: GENDER_OPTIONS }

  validates :age, numericality: {only_integer: true, greater_than: 0}

  belongs_to :open_mat
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true

  validates :email, presence: true,
                  format: /\A\S+@\S+\z/,
                  uniqueness: { case_sensitive: false }

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def require_signin
    unless current_user
      redirect_to new_session_url, alert: "Please sign in first!"
    end 
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/open_mats_controller.rb
class OpenMatsController < ApplicationController
  def index
    @open_mats = OpenMat.upcoming
  end

  def show
    @open_mat = OpenMat.find(params[:id])
  end

  def edit
    @open_mat = OpenMat.find(params[:id])
  end

  def update
    @open_mat = OpenMat.find(params[:id])
    if @open_mat.update(open_mat_params)
      redirect_to @open_mat
    else
      render :edit
    end
  end

  def new
    @open_mat = OpenMat.new
  end

  def create
    @open_mat = OpenMat.new(open_mat_params)
    if @open_mat.save
      redirect_to @open_mat
    else
      render :new
    end
  end 

  def destroy
    @open_mat = OpenMat.find(params[:id])
    @open_mat.destroy
    redirect_to open_mats_url
  end

  private

    def open_mat_params
      params.require(:open_mat).permit(:location, :host, :number_people_attending, :starts_at, :image_file_name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_open_mat

  def index
    @registrations = @open_mat.registrations
  end

  def new
    @registration = @open_mat.registrations.new
  end

  def create
    @registration = @open_mat.registrations.new(registration_params)
    if @registration.save
      redirect_to open_mat_registrations_path(@open_mat),
                      notice: "Thanks for your registration!"
    else
      render :new
    end
  end

private
  
  def registration_params
    params.require(:registration).permit(:name, :email, :gender, :age, :belt_level, :affiliation)
  end

  def set_open_mat
    @open_mat = OpenMat.find(params[:open_mat_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id 
      flash[:notice] = "Welcome back, #{user.name}!"
      redirect_to user 
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]

  def index 
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end 

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url, alert: "Account successfully deleted!"
  end

private

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/open_mats_helper.rb
module OpenMatsHelper
  def starts_in(open_mat)
    current_time = Time.now
    if open_mat.expired?
      content_tag(:strong, 'All Done!')
    else
      "Starts " + distance_of_time_in_words(current_time, open_mat.starts_at) + " from now"
    end
  end

  def image_for(open_mat)
    if open_mat.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag open_mat.image_file_name
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer style="text-align: center; padding: 5px; color: #237CBE; background: #F0F0F0">
  <p>
    Copyright &copy; 2016
    <%= link_to 'jitslist','http://jitslist.com' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header style="padding: 5px; color: #f0f0f0; background: #237cbe;">
    <h1>bjjhub</h1>
    <nav>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, current_user %>
          <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
        <% else %>
            <%= link_to 'Sign Up', signup_path, class: 'button' %>
            <%= link_to 'Sign In', new_session_path, class: 'button' %>
        <% end %>
      </p>
</nav>
</header>

app/views/layouts/_sidebar.html.erb
<aside style="float: right; background: #F0F0F0; width: 200px;">
  <nav>
    <ul>
      <li>
        <%= link_to 'All Open Mats', open_mats_path %>
      </li>
      <li>
        <%= link_to 'Add New Open mat', new_open_mat_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jitslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/sidebar' %>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/open_mats/_footer.html.erb
<footer>
  <p>
    Copyright &copy; 2016
    <%= link_to 'Jitslist, Inc.','http://jitslist.com' %>
  </p>
</footer>

app/views/open_mats/_form.html.erb
<%= form_for(@open_mat) do |f| %>
  <%= render "shared/errors", object: @open_mat %>
  <p>
    <%= f.label :location %><br/>
    <%= f.text_field :location, autofocus: true %>
  </p>
  <p>
    <%= f.label :host %><br/>
    <%= f.text_field :host %>
  </p>
  <p>
    <%= f.label :number_people_attending %>
    <%= f.number_field :number_people_attending %>
  </p>  
  <p>
    <%= f.label :starts_at %>
    <%= f.datetime_local_field :starts_at %>
  </p>
  <p>
    <%= f.label :image_file_name %><br/>
    <%= f.text_field :image_file_name, size: 30, placeholder: "GIF, JPG, or PNG file name" %>
  </p>
  <p>
    <%= f.submit %> |
    <%= link_to "Cancel", open_mats_path %>
  </p>
<% end %>

app/views/open_mats/edit.html.erb
<h1>Edit Open Mat</h1>

<%= render 'form' %>

app/views/open_mats/index.html.erb
<h1><%= pluralize(@open_mats.size, 'Open Mat') %></h1>

<% @open_mats.each do |open_mat| %>
  <article>
    <header>
      <h2><%= link_to open_mat.location, open_mat_path(open_mat), class: 'btn btn-primary btn-xs' %></h2>
    </header>
    <table>
      <tr>
        <th>Host:</th>
        <td><%= open_mat.host %></td>
      </tr>
      <tr>
        <th># People Attending:</th>
        <td><%= open_mat.number_people_attending %></td>
      </tr>
      <tr>
        <th>When:</th>
        <td><%= open_mat.starts_at %> (<%= starts_in(open_mat) %>)</td>
      </tr>
    </table>
  </article>
<% end %>

app/views/open_mats/new.html.erb
<h1>Create Open Mat</h1>

<%= render 'form' %>

app/views/open_mats/show.html.erb
<article>
  <h2>Location:</h2>
  <p>
    <%= @open_mat.location %>
  </p>
  <h3>Host:</h3>
  <p>
    <%= @open_mat.host %>
  </p><h3>When:</h3>
  <p>
    <%= @open_mat.starts_at %>
    <%= starts_in(@open_mat) %>
  </p>
  <h3><%= @open_mat.registrations.size %> People Attending:</h3>
  <p>
    <% @open_mat.registrations.each do |r| %>
    <li>
      <%= r.name %>
    </li>
  <% end %>
  </p>
  
  <%= image_for(@open_mat) %>

<%= link_to pluralize(@open_mat.registrations.size, "registration"), open_mat_registrations_path(@open_mat) %>

<footer>
  <%= link_to "Register!", new_open_mat_registration_path(@open_mat, class: "button ok register") %>

  <%= link_to "Edit", edit_open_mat_path(@open_mat), class: 'btn btn-info btn-xs' %>
  <%= link_to "Delete", open_mat_path(@open_mat), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
</footer>
</article>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved. 
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/errors", object: @user %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.email_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password %>
        <%= f.password_field :password, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <% if @user.new_record? %>
        <%= f.submit "Create Account" %>
      <% else %>
        <%= f.submit "Update Account" %>
      <% end %>
    </p>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
  <h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
  <h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
  <h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<article id="user">
  <header>
    <h1><%= @user.name %></h1>
    <h2><%= mail_to(@user.email) %></h2>
  </header>
  <footer>
    <nav>
      <%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
      <%= link_to 'Delete Account', @user,
                method: :delete,
                data: { confirm: 'Are you sure you want to permanently delete your account?' },
                class: 'button' %>
    </nav>
</footer>
</article>